### ISSUE TITLE
Invalid argument (pyfakewebcam.py, line 54)

### ISSUE THREAD

**Issue by thatkotov** [andreyryabtsev/BGMv2-webcam-plugin-linux#6]
My Garuda Arch couldn't install the thing (some Nvidia issues),
and Debian does this - and this is the issue -

```
python3 demo_webcam.py --model-checkpoint torchscript_mobilenetv2_fp16.pth
Traceback (most recent call last):
  File "/root/demo_webcam.py", line 586, in <module>
    fake_camera = pyfakewebcam.FakeWebcam(args.camera_device, cam.width, cam.height)
  File "/usr/local/lib/python3.9/dist-packages/pyfakewebcam/pyfakewebcam.py", line 54, in __init__
    fcntl.ioctl(self._video_device, _v4l2.VIDIOC_S_FMT, self._settings)
OSError: [Errno 22] Invalid argument
FATAL: exception not rethrown
Aborted
```

I tried pyfakewebcam from both apt & git

**Comment by charitarthchugh** [comment]
Have you tried changing the ``--camera-device`` flag? I had to set it to `/dev/video2` for it to work. 
Also do `ls /dev/ | grep video` to check all your webcams(virtual and real). Most likely, `/dev/video0` is your actual webcam. So switch between `/dev/video1`(default, see line 571 of `demo_webcam.py`) and all other webcams.

**Comment by charitarthchugh** [comment]
To be clear, this is not a problem of `pyfakewebcam`

**Comment by thatkotov** [comment]
Step forward!
So I run, say,
sudo modprobe v4l2loopback exclusive_caps=1 devices=1

v4l2-ctl --list-devices says:
```
Dummy video device (0x0000) (platform:v4l2loopback-000):
	/dev/video4
USB Video: USB Video (usb-0000:00:14.0-3.1.1):
	/dev/video2
	/dev/video3
	/dev/media1
HD WebCam: HD WebCam (usb-0000:00:14.0-7):
	/dev/video0
	/dev/video1
	/dev/media0
```
python3 demo_webcam.py --camera-device /dev/video4 --model-checkpoint torchscript_mobilenetv2_fp16.pth
says:
```
Traceback (most recent call last):
  File "/root/demo_webcam.py", line 589, in <module>
    preloaded_image = cv2_frame_to_cuda(cv2.imread(args.target_image))
  File "/root/demo_webcam.py", line 511, in cv2_frame_to_cuda
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ddpkm6fn/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
This video4 Dummy gets found well by Zoom now - it's my OBS output.
If I turn Zoom off & nothing else is connected to it & I run demo_webcam.py, the issue is the same.
It seems like the script can't see images from video4 for some reason.
I'm on another OS now, btw, Debian.

**Comment by andreyryabtsev** [comment]
Hmm, the traceback is from line 589, which reads not from the webcam but from args.target_image, so just the static image used as the virtual background. Is the image possibly missing? The "cvtColor" error usually happens when the file does not exist at the supplied path.

**Comment by thatkotov** [comment]
That's what I told. But Zoom worked well with this Dummy. Other apps too.
